[tool.poetry]
name = "work-1"
version = "0.1.0"
description = ""
authors = ["mexic <mexic2284@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
